package io.github.levij.orderflow.common.error;

public enum ErrorCode {
	VALIDATION_FAILED,
	MALFORMED_REQUEST,
	RESOURCE_NOT_FOUND,
	DUPLICATE_SKU,
	INSUFFICIENT_STOCK,
	EMAIL_ALREADY_REGISTERED,
	INVALID_CREDENTIALS,
	UNAUTHENTICATED,
	ACCESS_DENIED,
	DATA_CONFLICT,
	METHOD_NOT_ALLOWED,
	NOT_ACCEPTABLE,
	UNSUPPORTED_MEDIA_TYPE,
	INTERNAL_ERROR
}
