package io.github.levij.orderflow.common.error;

public enum ErrorCode {
	VALIDATION_FAILED,
	MALFORMED_REQUEST,
	RESOURCE_NOT_FOUND,
	DUPLICATE_SKU,
	INSUFFICIENT_STOCK,
	PRODUCT_NOT_AVAILABLE,
	INVALID_STATUS_TRANSITION,
	CONCURRENT_MODIFICATION,
	EMAIL_ALREADY_REGISTERED,
	INVALID_CREDENTIALS,
	UNAUTHENTICATED,
	ACCESS_DENIED,
	DATA_CONFLICT,
	METHOD_NOT_ALLOWED,
	NOT_ACCEPTABLE,
	UNSUPPORTED_MEDIA_TYPE,
	INTERNAL_ERROR
}
